// Class automatically generated by Dev-C++ New Class wizard

#ifndef BLOCK_H
#define BLOCK_H
#include "vertice.h"
// No description
class Block
{
	public:
		// class constructor
		Block();
		// class destructor
		~Block();
		void Rendered(int Hi);
		void TTT(float x,float y,float z);
		bool BeRendered;
		int R;
		Vertice TBRen;
		float x,y,z;
		bool Top,Bottom,Left,Right,Front,Back;
};

#endif // BLOCK_H
