// Class automatically generated by Dev-C++ New Class wizard

#include "block.h" // class's header file
// class constructor
Block::Block()
{
       Top=true;
	   Bottom=true;
	   Left=true;
	   Right=true;
	   Front=true;
	   Back=true;      
}

// class destructor
Block::~Block()
{
	// insert your code here
}
void Block::Rendered(int Hi)
{
	if(Hi==0)
	{
    BeRendered=false;         
    }else
    {
    BeRendered=true;
    } 
};
void Block::TTT(float X,float Y,float Z)
{
     x=X;
     y=Y;
     z=Z;
};
