// Class automatically generated by Dev-C++ New Class wizard

#ifndef VERTICE_H
#define VERTICE_H

/*
 * No description
 */
class Vertice
{
	public:
		// class constructor
		Vertice(float f1,float f2,float f3);
		Vertice::Vertice();
		void Vertice::AddDefault(float f1,float f2,float f3);
		// class destructor
		~Vertice();
        float CoordinateX;
        float CoordinateY;
        float CoordinateZ;
		
};

#endif // VERTICE_H
