// Class automatically generated by Dev-C++ New Class wizard

#include "vertice.h" // class's header file

// class constructor
Vertice::Vertice(float f1,float f2,float f3)
{
	CoordinateX=f1;
    CoordinateY=f2;
    CoordinateZ=f3;
}
Vertice::Vertice()
{
	
}
// class destructor
Vertice::~Vertice()
{
	// insert your code here
}
void Vertice::AddDefault(float f1,float f2,float f3)
{
	CoordinateX=f1;
    CoordinateY=f2;
    CoordinateZ=f3;
}
